import type {
  IPConfig,
  PortConfig,
  RegisterEntry,
  GeneratedFiles,
  ClockConfig,
  ResetConfig,
} from './types';
import { PortType } from './types';
import { calcAddrWidth, countPhysicalRegs, formatAddress } from './registerMap';

// ─────────────────────────────────────────────────────────────────────────────
// Port rendering helpers
// ─────────────────────────────────────────────────────────────────────────────

function verilogPortDecl(pc: PortConfig): string {
  const p = pc.port;
  const dir = p.direction === 'input' ? 'input  wire' :
              p.direction === 'output' ? 'output wire' : 'inout  wire';
  const sign = p.signed ? ' signed' : '';
  const width = p.width > 1 ? ` [${p.msb}:${p.lsb}]` : '';
  return `    ${dir}${sign}${width} ${p.name}`;
}

function externalPorts(portConfigs: PortConfig[], clock: ClockConfig | null, reset: ResetConfig | null): string {
  const lines: string[] = [];
  for (const pc of portConfigs) {
    const t = pc.portType;
    if (t === PortType.EXTERNAL_INPUT || t === PortType.EXTERNAL_OUTPUT || t === PortType.EXTERNAL_INOUT) {
      lines.push(verilogPortDecl(pc) + ',');
    }
    if (t === PortType.CLOCK && clock && !clock.useAxiClock) {
      lines.push(verilogPortDecl(pc) + ',');
    }
    if (t === PortType.RESET && reset && !reset.useAxiReset) {
      lines.push(verilogPortDecl(pc) + ',');
    }
  }
  return lines.join('\n');
}

function moduleInstantiation(cfg: IPConfig): string {
  const { portConfigs, registers, clock, reset } = cfg;
  const topModName = cfg.ipName.replace(/_axi$/i, '');
  const lines: string[] = [];
  lines.push(`    ${topModName} u_${topModName} (`);
  const mappings: string[] = [];

  for (const pc of portConfigs) {
    const p = pc.port;
    switch (pc.portType) {
      case PortType.CLOCK: {
        const sig = clock?.useAxiClock ? 'S_AXI_ACLK' : p.name;
        mappings.push(`        .${p.name}(${sig})`);
        break;
      }
      case PortType.RESET: {
        const sig = reset?.useAxiReset ? 'S_AXI_ARESETN' : p.name;
        mappings.push(`        .${p.name}(${sig})`);
        break;
      }
      case PortType.AXI_REGISTER: {
        // Find all register entries for this port (could be packed)
        const reg = registers.find(r => r.mappedPort === p.name);
        if (reg) {
          // Drive port from the correct slice of the 32-bit register word
          const needsSlice = p.width < 32;
          const slice = needsSlice ? `[${reg.msb}:${reg.lsb}]` : '';
          mappings.push(`        .${p.name}(${reg.regName}${slice})`);
        } else {
          mappings.push(`        .${p.name}(/* unassigned */)`);
        }
        break;
      }
      case PortType.EXTERNAL_INPUT:
      case PortType.EXTERNAL_OUTPUT:
      case PortType.EXTERNAL_INOUT:
        mappings.push(`        .${p.name}(${p.name})`);
        break;
      case PortType.IGNORE:
        break;
    }
  }
  lines.push(mappings.join(',\n'));
  lines.push('    );');
  return lines.join('\n');
}

// ─────────────────────────────────────────────────────────────────────────────
// Top wrapper generator
// ─────────────────────────────────────────────────────────────────────────────

function generateTopWrapper(cfg: IPConfig): string {
  const physRegs = countPhysicalRegs(cfg.registers);
  const addrWidth = calcAddrWidth(physRegs);
  const userPorts = externalPorts(cfg.portConfigs, cfg.clock, cfg.reset);
  const slaveInst = generateSlaveInstantiation(cfg);

  return `\`timescale 1 ns / 1 ps
// =============================================================================
// ${cfg.ipName}
// Auto-generated AXI4-Lite wrapper for module: ${cfg.ipName.replace(/_axi$/i, '')}
// Generated by Axinator — Verilog AXI Wrapper Generator
// =============================================================================

module ${cfg.ipName} #
(
    parameter integer C_S00_AXI_DATA_WIDTH = 32,
    parameter integer C_S00_AXI_ADDR_WIDTH = ${addrWidth}
)
(
${userPorts ? userPorts + '\n' : ''}    // AXI4-Lite Slave Ports
    input wire  s00_axi_aclk,
    input wire  s00_axi_aresetn,
    input wire [C_S00_AXI_ADDR_WIDTH-1 : 0] s00_axi_awaddr,
    input wire [2 : 0] s00_axi_awprot,
    input wire  s00_axi_awvalid,
    output wire  s00_axi_awready,
    input wire [C_S00_AXI_DATA_WIDTH-1 : 0] s00_axi_wdata,
    input wire [(C_S00_AXI_DATA_WIDTH/8)-1 : 0] s00_axi_wstrb,
    input wire  s00_axi_wvalid,
    output wire  s00_axi_wready,
    output wire [1 : 0] s00_axi_bresp,
    output wire  s00_axi_bvalid,
    input wire  s00_axi_bready,
    input wire [C_S00_AXI_ADDR_WIDTH-1 : 0] s00_axi_araddr,
    input wire [2 : 0] s00_axi_arprot,
    input wire  s00_axi_arvalid,
    output wire  s00_axi_arready,
    output wire [C_S00_AXI_DATA_WIDTH-1 : 0] s00_axi_rdata,
    output wire [1 : 0] s00_axi_rresp,
    output wire  s00_axi_rvalid,
    input wire  s00_axi_rready
);

// Instantiation of AXI4-Lite slave
${slaveInst}

endmodule
`;
}

function generateSlaveInstantiation(cfg: IPConfig): string {
  const slaveName = `${cfg.ipName}_S00_AXI`;
  const externalPortMappings = cfg.portConfigs.filter(pc =>
    pc.portType === PortType.EXTERNAL_INPUT ||
    pc.portType === PortType.EXTERNAL_OUTPUT ||
    pc.portType === PortType.EXTERNAL_INOUT ||
    (pc.portType === PortType.CLOCK && cfg.clock && !cfg.clock.useAxiClock) ||
    (pc.portType === PortType.RESET && cfg.reset && !cfg.reset.useAxiReset)
  ).map(pc => `        .${pc.port.name}(${pc.port.name})`).join(',\n');

  return `    ${slaveName} # (
        .C_S_AXI_DATA_WIDTH(C_S00_AXI_DATA_WIDTH),
        .C_S_AXI_ADDR_WIDTH(C_S00_AXI_ADDR_WIDTH)
    ) ${slaveName}_inst (
${externalPortMappings ? externalPortMappings + ',\n' : ''}        .S_AXI_ACLK(s00_axi_aclk),
        .S_AXI_ARESETN(s00_axi_aresetn),
        .S_AXI_AWADDR(s00_axi_awaddr),
        .S_AXI_AWPROT(s00_axi_awprot),
        .S_AXI_AWVALID(s00_axi_awvalid),
        .S_AXI_AWREADY(s00_axi_awready),
        .S_AXI_WDATA(s00_axi_wdata),
        .S_AXI_WSTRB(s00_axi_wstrb),
        .S_AXI_WVALID(s00_axi_wvalid),
        .S_AXI_WREADY(s00_axi_wready),
        .S_AXI_BRESP(s00_axi_bresp),
        .S_AXI_BVALID(s00_axi_bvalid),
        .S_AXI_BREADY(s00_axi_bready),
        .S_AXI_ARADDR(s00_axi_araddr),
        .S_AXI_ARPROT(s00_axi_arprot),
        .S_AXI_ARVALID(s00_axi_arvalid),
        .S_AXI_ARREADY(s00_axi_arready),
        .S_AXI_RDATA(s00_axi_rdata),
        .S_AXI_RRESP(s00_axi_rresp),
        .S_AXI_RVALID(s00_axi_rvalid),
        .S_AXI_RREADY(s00_axi_rready)
    );`;
}

// ─────────────────────────────────────────────────────────────────────────────
// AXI Slave generator helpers
// ─────────────────────────────────────────────────────────────────────────────

function generateRegisterDeclarations(registers: RegisterEntry[]): string {
  if (registers.length === 0) return '    // No AXI registers configured';
  // Emit one declaration per unique register name (packed pairs share a reg)
  const seen = new Set<string>();
  const lines: string[] = [];
  for (const r of registers) {
    if (!seen.has(r.regName)) {
      seen.add(r.regName);
      lines.push(`    reg [C_S_AXI_DATA_WIDTH-1:0] ${r.regName};`);
    }
  }
  return lines.join('\n');
}

/**
 * Build write logic that is correct for sub-32-bit ports.
 *
 * Key fix: byte-enable guards now use proper constant expressions.
 * The byte-enable loop only touches bytes that actually overlap with the
 * port's slice. For a [15:0] port that lives in bits [15:0] of the register,
 * only byte lanes 0 (bits 7:0) and 1 (bits 15:8) are relevant.
 */
function generateWriteLogic(registers: RegisterEntry[]): string {
  // Collect unique physical registers (by address) for the case statement
  const physMap = new Map<number, RegisterEntry[]>();
  for (const r of registers) {
    if (r.mode === 'RO') continue;
    if (!physMap.has(r.address)) physMap.set(r.address, []);
    physMap.get(r.address)!.push(r);
  }

  if (physMap.size === 0) return '            // No writable registers';

  const physAddrs = Array.from(physMap.keys()).sort((a, b) => a - b);

  const cases = physAddrs.map(addr => {
    const addrIdx = addr / 4;
    const entries = physMap.get(addr)!;
    // For each entry in this physical register, generate byte-enable writes
    // that only touch bytes within [msb:lsb]
    const byteLines: string[] = [];
    for (let byte = 0; byte < 4; byte++) {
      const bitH = byte * 8 + 7;
      const bitL = byte * 8;
      // Check if this byte overlaps with any entry's slice
      const overlapping = entries.filter(e => e.lsb <= bitH && e.msb >= bitL);
      if (overlapping.length === 0) continue;
      // Clamp the bit range to actual slice boundaries
      for (const e of overlapping) {
        const hi = Math.min(bitH, e.msb);
        const lo = Math.max(bitL, e.lsb);
        byteLines.push(
          `                        if (S_AXI_WSTRB[${byte}] == 1) begin\n` +
          `                            ${e.regName}[${hi}:${lo}] <= S_AXI_WDATA[${hi}:${lo}];\n` +
          `                        end`
        );
      }
    }
    return `                    ${addrIdx}: begin\n${byteLines.join('\n')}\n                    end`;
  }).join('\n');

  // Default: hold all writable registers
  const uniqueRegs = [...new Set(
    Array.from(physMap.values()).flat().map(r => r.regName)
  )];
  const holdLines = uniqueRegs.map(n => `                        ${n} <= ${n};`).join('\n');

  return `                    case ( axi_awaddr[ADDR_LSB+OPT_MEM_ADDR_BITS:ADDR_LSB] )
${cases}
                    default : begin
${holdLines}
                    end
                    endcase`;
}

function generateReadLogic(registers: RegisterEntry[]): string {
  if (registers.length === 0) {
    return `                    // No registers to read
                    reg_data_out <= 0;`;
  }

  // Build one case entry per physical address
  const physMap = new Map<number, RegisterEntry[]>();
  for (const r of registers) {
    if (!physMap.has(r.address)) physMap.set(r.address, []);
    physMap.get(r.address)!.push(r);
  }

  const physAddrs = Array.from(physMap.keys()).sort((a, b) => a - b);
  const cases = physAddrs.map(addr => {
    const addrIdx = addr / 4;
    const entries = physMap.get(addr)!;
    // The register word is the same for all entries at this address
    const regName = entries[0].regName;
    const isWO = entries.every(e => e.mode === 'WO');
    const rval = isWO ? `{C_S_AXI_DATA_WIDTH{1'b0}}` : regName;
    return `                    ${addrIdx}: reg_data_out <= ${rval};`;
  }).join('\n');

  return `                    case ( axi_araddr[ADDR_LSB+OPT_MEM_ADDR_BITS:ADDR_LSB] )
${cases}
                    default: reg_data_out <= 0;
                    endcase`;
}

function generateSlaveExternalPorts(cfg: IPConfig): string {
  const lines: string[] = [];
  for (const pc of cfg.portConfigs) {
    const t = pc.portType;
    if (t === PortType.EXTERNAL_INPUT || t === PortType.EXTERNAL_OUTPUT || t === PortType.EXTERNAL_INOUT) {
      lines.push(verilogPortDecl(pc) + ',');
    }
    if (t === PortType.CLOCK && cfg.clock && !cfg.clock.useAxiClock) {
      lines.push(verilogPortDecl(pc) + ',');
    }
    if (t === PortType.RESET && cfg.reset && !cfg.reset.useAxiReset) {
      lines.push(verilogPortDecl(pc) + ',');
    }
  }
  return lines.join('\n');
}

// ─────────────────────────────────────────────────────────────────────────────
// AXI Slave top-level generator
// ─────────────────────────────────────────────────────────────────────────────

function generateAxiSlave(cfg: IPConfig): string {
  const { registers } = cfg;

  // OPT_MEM_ADDR_BITS must cover the index range [0 .. numPhysRegs-1].
  // The case statement uses axi_awaddr[ADDR_LSB+OPT_MEM_ADDR_BITS : ADDR_LSB]
  // which is (OPT_MEM_ADDR_BITS+1) bits wide.
  // We need (OPT_MEM_ADDR_BITS+1) >= ceil(log2(numPhysRegs)), so:
  //   OPT_MEM_ADDR_BITS = max(ceil(log2(numPhysRegs)) - 1, 0)
  // Special case: 0 or 1 physical registers → 0 (1-bit selector, value 0).
  const physRegs = countPhysicalRegs(registers);
  const addrWidth = calcAddrWidth(physRegs);
  const optMemAddrBits = physRegs <= 1 ? 0 : Math.ceil(Math.log2(physRegs)) - 1;

  const slaveName = `${cfg.ipName}_S00_AXI`;
  const slaveExternalPorts = generateSlaveExternalPorts(cfg);
  const regDecls = generateRegisterDeclarations(registers);
  const writeLogic = generateWriteLogic(registers);
  const readLogic = generateReadLogic(registers);
  const modInst = moduleInstantiation(cfg);

  // Reset lines — one per unique register
  const uniqueRegs = [...new Set(registers.map(r => r.regName))];
  const resetLines = uniqueRegs.length > 0
    ? uniqueRegs.map(n => `        ${n} <= 0;`).join('\n')
    : '        // No registers to reset';

  return `\`timescale 1 ns / 1 ps
// =============================================================================
// ${slaveName}
// AXI4-Lite Slave — standard Vivado template
// Generated by Axinator — Verilog AXI Wrapper Generator
// =============================================================================

module ${slaveName} #
(
    parameter integer C_S_AXI_DATA_WIDTH = 32,
    parameter integer C_S_AXI_ADDR_WIDTH = ${addrWidth}
)
(
    // Users to add ports here
${slaveExternalPorts ? slaveExternalPorts + '\n' : ''}    // User ports ends
    input wire  S_AXI_ACLK,
    input wire  S_AXI_ARESETN,
    input wire [C_S_AXI_ADDR_WIDTH-1 : 0] S_AXI_AWADDR,
    input wire [2 : 0] S_AXI_AWPROT,
    input wire  S_AXI_AWVALID,
    output wire  S_AXI_AWREADY,
    input wire [C_S_AXI_DATA_WIDTH-1 : 0] S_AXI_WDATA,
    input wire [(C_S_AXI_DATA_WIDTH/8)-1 : 0] S_AXI_WSTRB,
    input wire  S_AXI_WVALID,
    output wire  S_AXI_WREADY,
    output wire [1 : 0] S_AXI_BRESP,
    output wire  S_AXI_BVALID,
    input wire  S_AXI_BREADY,
    input wire [C_S_AXI_ADDR_WIDTH-1 : 0] S_AXI_ARADDR,
    input wire [2 : 0] S_AXI_ARPROT,
    input wire  S_AXI_ARVALID,
    output wire  S_AXI_ARREADY,
    output wire [C_S_AXI_DATA_WIDTH-1 : 0] S_AXI_RDATA,
    output wire [1 : 0] S_AXI_RRESP,
    output wire  S_AXI_RVALID,
    input wire  S_AXI_RREADY
);

reg [C_S_AXI_ADDR_WIDTH-1 : 0]  axi_awaddr;
reg   axi_awready;
reg   axi_wready;
reg [1 : 0]  axi_bresp;
reg   axi_bvalid;
reg [C_S_AXI_ADDR_WIDTH-1 : 0]  axi_araddr;
reg   axi_arready;
reg [C_S_AXI_DATA_WIDTH-1 : 0]  axi_rdata;
reg [1 : 0]  axi_rresp;
reg   axi_rvalid;

// ADDR_LSB = 2 for 32-bit data bus (word-aligned addressing)
localparam integer ADDR_LSB = (C_S_AXI_DATA_WIDTH/32) + 1;
// OPT_MEM_ADDR_BITS: number of additional address bits above ADDR_LSB
// needed to index all registers. Selector width = OPT_MEM_ADDR_BITS+1 bits.
localparam integer OPT_MEM_ADDR_BITS = ${optMemAddrBits};

${regDecls}
reg [C_S_AXI_DATA_WIDTH-1:0]  reg_data_out;
integer  byte_index;
reg  aw_en;

assign S_AXI_AWREADY = axi_awready;
assign S_AXI_WREADY  = axi_wready;
assign S_AXI_BRESP   = axi_bresp;
assign S_AXI_BVALID  = axi_bvalid;
assign S_AXI_ARREADY = axi_arready;
assign S_AXI_RDATA   = axi_rdata;
assign S_AXI_RRESP   = axi_rresp;
assign S_AXI_RVALID  = axi_rvalid;

// Write address handshake
always @( posedge S_AXI_ACLK )
begin
    if ( S_AXI_ARESETN == 1'b0 ) begin axi_awready <= 1'b0; aw_en <= 1'b1; end
    else begin
        if (~axi_awready && S_AXI_AWVALID && S_AXI_WVALID && aw_en) begin
            axi_awready <= 1'b1; aw_en <= 1'b0;
        end else if (S_AXI_BREADY && axi_bvalid) begin
            aw_en <= 1'b1; axi_awready <= 1'b0;
        end else begin axi_awready <= 1'b0; end
    end
end

always @( posedge S_AXI_ACLK )
begin
    if ( S_AXI_ARESETN == 1'b0 ) axi_awaddr <= 0;
    else if (~axi_awready && S_AXI_AWVALID && S_AXI_WVALID && aw_en) axi_awaddr <= S_AXI_AWADDR;
end

// Write data handshake
always @( posedge S_AXI_ACLK )
begin
    if ( S_AXI_ARESETN == 1'b0 ) axi_wready <= 1'b0;
    else begin
        if (~axi_wready && S_AXI_WVALID && S_AXI_AWVALID && aw_en) axi_wready <= 1'b1;
        else axi_wready <= 1'b0;
    end
end

wire slv_reg_wren;
assign slv_reg_wren = axi_wready && S_AXI_WVALID && axi_awready && S_AXI_AWVALID;

// Register write logic
always @( posedge S_AXI_ACLK )
begin
    if ( S_AXI_ARESETN == 1'b0 ) begin
${resetLines}
    end else begin
        if (slv_reg_wren) begin
${writeLogic}
        end
    end
end

// Write response
always @( posedge S_AXI_ACLK )
begin
    if ( S_AXI_ARESETN == 1'b0 ) begin axi_bvalid <= 0; axi_bresp <= 2'b0; end
    else begin
        if (axi_awready && S_AXI_AWVALID && ~axi_bvalid && axi_wready && S_AXI_WVALID) begin
            axi_bvalid <= 1'b1; axi_bresp <= 2'b0;
        end else if (S_AXI_BREADY && axi_bvalid) begin axi_bvalid <= 1'b0; end
    end
end

// Read address handshake
always @( posedge S_AXI_ACLK )
begin
    if ( S_AXI_ARESETN == 1'b0 ) begin axi_arready <= 1'b0; axi_araddr <= 32'b0; end
    else begin
        if (~axi_arready && S_AXI_ARVALID) begin axi_arready <= 1'b1; axi_araddr <= S_AXI_ARADDR; end
        else axi_arready <= 1'b0;
    end
end

// Read data handshake
always @( posedge S_AXI_ACLK )
begin
    if ( S_AXI_ARESETN == 1'b0 ) begin axi_rvalid <= 0; axi_rresp <= 0; end
    else begin
        if (axi_arready && S_AXI_ARVALID && ~axi_rvalid) begin axi_rvalid <= 1'b1; axi_rresp <= 2'b0; end
        else if (axi_rvalid && S_AXI_RREADY) axi_rvalid <= 1'b0;
    end
end

wire slv_reg_rden;
assign slv_reg_rden = axi_arready & S_AXI_ARVALID & ~axi_rvalid;

// Register read mux
always @(*)
begin
${readLogic}
end

always @( posedge S_AXI_ACLK )
begin
    if ( S_AXI_ARESETN == 1'b0 ) axi_rdata <= 0;
    else if (slv_reg_rden) axi_rdata <= reg_data_out;
end

// =============================================================================
// User logic — instantiate top module
// =============================================================================
${modInst}

endmodule
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Register map markdown
// ─────────────────────────────────────────────────────────────────────────────

function generateRegMapMd(cfg: IPConfig): string {
  const physRegs = countPhysicalRegs(cfg.registers);
  const addrWidth = calcAddrWidth(physRegs);

  // De-duplicate rows by address for the table header, show all entries (packed ports each get a row)
  const rows = cfg.registers.map(r =>
    `| ${formatAddress(r.address)} | ${r.regName}[${r.msb}:${r.lsb}] | ${r.mappedPort} | ${r.width} | ${r.mode} |`
  ).join('\n');

  return `# Register Map: ${cfg.ipName}

| Address | Register Slice | Mapped Port | Width | Mode |
|---------|---------------|-------------|-------|------|
${rows || '| — | — | No AXI registers configured | — | — |'}

## Notes
- Packed pairs: two ports with width ≤ 16 share one 32-bit register word.
  Low half [15:0] = first port, high half [31:16] = second port.

## Address Width
\`C_S_AXI_ADDR_WIDTH = ${addrWidth}\`

## AXI Access Example (C pseudocode)
\`\`\`c
#define BASE_ADDR  0x43C00000  // example Zynq AXI GP base

${cfg.registers.map(r =>
  `// ${r.mappedPort} → ${r.regName}[${r.msb}:${r.lsb}]\n*(volatile uint32_t*)(BASE_ADDR + ${formatAddress(r.address)}) = value;`
).join('\n') || '// No registers configured'}
\`\`\`
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// C driver (.h + .c)
// Gives firmware a typed, register-map-aware API so the IP is controllable
// from C out of the box (e.g. MicroBlaze / Zynq / RISC-V soft-core).
// ─────────────────────────────────────────────────────────────────────────────

function cIdent(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, '_').toUpperCase();
}

function generateDriverHeader(cfg: IPConfig): string {
  const up = cIdent(cfg.ipName);
  const portRow =
    (r: RegisterEntry) =>
      `/* ${r.mappedPort} -> ${r.regName}[${r.msb}:${r.lsb}] (${r.width} bit, ${r.mode}) */`;

  const accessors = cfg.registers
    .filter(r => r.mode !== 'RO')
    .map(r => {
      const fn = `${cfg.ipName}_set_${r.mappedPort}`;
      const argType = r.width <= 32 && r.width > 16 ? 'uint32_t' : 'uint32_t';
      return `${portRow(r)}\nvoid ${fn}(${argType} value);`;
    }).join('\n');

  const readers = cfg.registers
    .filter(r => r.mode !== 'WO')
    .map(r => {
      const fn = `${cfg.ipName}_get_${r.mappedPort}`;
      return `${portRow(r)}\nuint32_t ${fn}(void);`;
    }).join('\n');

  return `/** ${cfg.ipName} — autogenerated C driver.
 * Peripheral base address is an example; redefine ${up}_BASE at build time
 * (or override in the Makefile / linker script) with the value Vivado assigns
 * in the address map (see the block design address editor).
 */
#ifndef ${up}_DRIVER_H
#define ${up}_DRIVER_H

#include <stdint.h>

#ifndef ${up}_BASE
#define ${up}_BASE 0x43C00000U
#endif

/* --- Register offset access --- */
uint32_t ${cfg.ipName}_read(uint32_t offset);
void     ${cfg.ipName}_write(uint32_t offset, uint32_t value);

/* --- Per-port accessors (register-slice aware; packed-word RMW handled) --- */
${accessors}
${readers}

#endif /* ${up}_DRIVER_H */
`;
}

function generateDriverSource(cfg: IPConfig): string {
  const up = cIdent(cfg.ipName);
  const regConsts = Array.from(
    new Map(cfg.registers.map(r => [r.address, r])).values()
  ).map(r =>
    `#define ${up}_REG_${cIdent(r.regName)}_OFFSET ${formatAddress(r.address)}U  /* ${r.regName} */`
  ).join('\n');

  // Per port: set (RMW with mask) and get
  const fns = cfg.registers.map(r => {
    const mask = ((1 << r.width) - 1);
    const maskHex = `0x${mask.toString(16).toUpperCase()}U`;
    const msb = r.msb, lsb = r.lsb;
    const out: string[] = [];
    if (r.mode !== 'RO') {
      out.push(
        `void ${cfg.ipName}_set_${r.mappedPort}(uint32_t value) {\n` +
        `    uint32_t word = ${cfg.ipName}_read(${formatAddress(r.address)}U);\n` +
        `    word &= ~(${maskHex} << ${lsb});\n` +
        `    word |= (value & ${maskHex}) << ${lsb};\n` +
        `    ${cfg.ipName}_write(${formatAddress(r.address)}U, word);\n` +
        `}\n`
      );
    }
    if (r.mode !== 'WO') {
      out.push(
        `uint32_t ${cfg.ipName}_get_${r.mappedPort}(void) {\n` +
        `    return (${cfg.ipName}_read(${formatAddress(r.address)}U) >> ${lsb}) & ${maskHex};\n` +
        `}\n`
      );
    }
    return `/* ${r.mappedPort} -> ${r.regName}[${r.msb}:${r.lsb}] (${r.width} bit, ${r.mode}) */\n${out.join('\n')}`;
  }).join('\n');

  return `/* ${cfg.ipName} — autogenerated C driver implementation. */
#include "${cfg.ipName}_driver.h"

${regConsts}

uint32_t ${cfg.ipName}_read(uint32_t offset) {
    return *(volatile uint32_t *)(${up}_BASE + offset);
}

void ${cfg.ipName}_write(uint32_t offset, uint32_t value) {
    *(volatile uint32_t *)(${up}_BASE + offset) = value;
}

${fns}
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// component.xml
// ─────────────────────────────────────────────────────────────────────────────

function generateComponentXml(cfg: IPConfig): string {
  const physRegs = countPhysicalRegs(cfg.registers);
  const addrWidth = calcAddrWidth(physRegs);
  const sourceFileEntries = cfg.sourceFiles.map(f =>
    `      <spirit:file>\n        <spirit:name>hdl/${f.filename}</spirit:name>\n        <spirit:fileType>verilogSource</spirit:fileType>\n      </spirit:file>`
  ).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Vivado IP-XACT component descriptor for: ${cfg.ipName}
  Generated by Axinator — Verilog AXI Wrapper Generator
-->
<spirit:component xmlns:xilinx="http://www.xilinx.com"
                  xmlns:spirit="http://www.spiritconsortium.org/XMLSchema/SPIRIT/1685-2009/Schema"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <spirit:vendor>user</spirit:vendor>
  <spirit:library>ip</spirit:library>
  <spirit:name>${cfg.ipName}</spirit:name>
  <spirit:version>1.0</spirit:version>

  <spirit:busInterfaces>
    <spirit:busInterface>
      <spirit:name>S00_AXI</spirit:name>
      <spirit:busType spirit:vendor="xilinx.com" spirit:library="interface"
                      spirit:name="aximm" spirit:version="1.0"/>
      <spirit:abstractionType spirit:vendor="xilinx.com" spirit:library="interface"
                              spirit:name="aximm_rtl" spirit:version="1.0"/>
      <spirit:slave/>
      <spirit:parameters>
        <spirit:parameter>
          <spirit:name>DATA_WIDTH</spirit:name><spirit:value>32</spirit:value>
        </spirit:parameter>
        <spirit:parameter>
          <spirit:name>ADDR_WIDTH</spirit:name><spirit:value>${addrWidth}</spirit:value>
        </spirit:parameter>
      </spirit:parameters>
    </spirit:busInterface>
  </spirit:busInterfaces>

  <spirit:fileSets>
    <spirit:fileSet>
      <spirit:name>xilinx_verilogsynthesis_view_fileset</spirit:name>
      <spirit:file>
        <spirit:name>hdl/${cfg.ipName}.v</spirit:name>
        <spirit:fileType>verilogSource</spirit:fileType>
      </spirit:file>
      <spirit:file>
        <spirit:name>hdl/${cfg.ipName}_S00_AXI.v</spirit:name>
        <spirit:fileType>verilogSource</spirit:fileType>
      </spirit:file>
      <spirit:file>
        <spirit:name>driver/${cfg.ipName}_driver.h</spirit:name>
        <spirit:fileType>text</spirit:fileType>
      </spirit:file>
      <spirit:file>
        <spirit:name>driver/${cfg.ipName}_driver.c</spirit:name>
        <spirit:fileType>text</spirit:fileType>
      </spirit:file>
${sourceFileEntries}
    </spirit:fileSet>
  </spirit:fileSets>

  <spirit:parameters>
    <spirit:parameter>
      <spirit:name>C_S00_AXI_DATA_WIDTH</spirit:name>
      <spirit:value spirit:format="long">32</spirit:value>
    </spirit:parameter>
    <spirit:parameter>
      <spirit:name>C_S00_AXI_ADDR_WIDTH</spirit:name>
      <spirit:value spirit:format="long">${addrWidth}</spirit:value>
    </spirit:parameter>
  </spirit:parameters>
</spirit:component>
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// README
// ─────────────────────────────────────────────────────────────────────────────

function generateReadme(cfg: IPConfig): string {
  const physRegs = countPhysicalRegs(cfg.registers);
  const addrWidth = calcAddrWidth(physRegs);
  const topModName = cfg.ipName.replace(/_axi$/i, '');
  const extPorts = cfg.portConfigs.filter(pc =>
    pc.portType === PortType.EXTERNAL_INPUT ||
    pc.portType === PortType.EXTERNAL_OUTPUT ||
    pc.portType === PortType.EXTERNAL_INOUT
  );
  const sourceFileRows = cfg.sourceFiles.map(f =>
    `| \`hdl/${f.filename}\` | Original RTL source |`
  ).join('\n');

  return `# ${cfg.ipName}

Auto-generated AXI4-Lite IP wrapper for Verilog module **${topModName}**.
Generated by **Axinator — Verilog AXI Wrapper Generator**.

---

## Design Hierarchy

\`\`\`
${cfg.ipName}  (AXI wrapper — generated)
    └── ${topModName}  (top RTL module)
        └── ... (internal hierarchy — unchanged)
\`\`\`

---

## Files

| File | Description |
|------|-------------|
| \`hdl/${cfg.ipName}.v\` | Top-level AXI wrapper (generated) |
| \`hdl/${cfg.ipName}_S00_AXI.v\` | AXI4-Lite slave (generated) |
| \`driver/${cfg.ipName}_driver.h\` | C driver header (register constants + accessors) |
| \`driver/${cfg.ipName}_driver.c\` | C driver source |
${sourceFileRows}
| \`component.xml\` | Vivado IP-XACT descriptor |

---

## IP Parameters

| Parameter | Value |
|-----------|-------|
| \`C_S00_AXI_DATA_WIDTH\` | 32 |
| \`C_S00_AXI_ADDR_WIDTH\` | ${addrWidth} |

---

## Register Map

| Address | Register Slice | Port | Mode |
|---------|---------------|------|------|
${cfg.registers.map(r => `| ${formatAddress(r.address)} | \`${r.regName}[${r.msb}:${r.lsb}]\` | \`${r.mappedPort}\` | ${r.mode} |`).join('\n') || '| — | — | No AXI registers | — |'}

---

## External Ports

| Port | Direction | Width |
|------|-----------|-------|
${extPorts.map(pc => `| \`${pc.port.name}\` | ${pc.port.direction} | ${pc.port.width} |`).join('\n') || '| — | — | No external ports |'}

---

## Clock & Reset

${cfg.clock ? `- **Clock**: \`${cfg.clock.portName}\`${cfg.clock.useAxiClock ? ' → \`S_AXI_ACLK\`' : ' (external)'}` : '- No clock configured'}
${cfg.reset ? `- **Reset**: \`${cfg.reset.portName}\`, ${cfg.reset.polarity}${cfg.reset.useAxiReset ? ' → \`S_AXI_ARESETN\`' : ' (external)'}` : '- No reset configured'}

---

## AXI Access Example

\`\`\`c
#include <stdint.h>

#define ${cfg.ipName.toUpperCase()}_BASE  0x43C00000

${cfg.registers.map(r =>
  `#define ${r.mappedPort.toUpperCase()}_OFFSET  ${formatAddress(r.address)}  // ${r.regName}[${r.msb}:${r.lsb}]`
).join('\n') || '// No registers configured'}

static inline void ${cfg.ipName}_write(uint32_t offset, uint32_t val) {
    *(volatile uint32_t*)(${cfg.ipName.toUpperCase()}_BASE + offset) = val;
}

static inline uint32_t ${cfg.ipName}_read(uint32_t offset) {
    return *(volatile uint32_t*)(${cfg.ipName.toUpperCase()}_BASE + offset);
}
\`\`\`

---

## Vivado Integration

1. Copy this directory to your Vivado IP repository path.
2. In Vivado: **Settings → IP → Repository** → add the parent directory.
3. Use **IP Packager** to complete the \`component.xml\` metadata if needed.
4. Add the IP to your block design via **IP Catalog**.

> **Note:** The internal RTL hierarchy (\`${topModName}\` and its sub-modules) is preserved
> unchanged. The AXI wrapper only adds the AXI4-Lite register interface on top.
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Main entry point
// ─────────────────────────────────────────────────────────────────────────────

export function generateAll(cfg: IPConfig): GeneratedFiles {
  const sourceMap = new Map<string, string>();
  for (const f of cfg.sourceFiles) {
    sourceMap.set(f.filename, f.content);
  }

  return {
    topWrapper:    generateTopWrapper(cfg),
    axiSlave:      generateAxiSlave(cfg),
    sourceMap,
    registerMapMd: generateRegMapMd(cfg),
    componentXml:  generateComponentXml(cfg),
    readme:        generateReadme(cfg),
    driverHeader:  generateDriverHeader(cfg),
    driverSource:  generateDriverSource(cfg),
  };
}
